#docker-compose.yml
version: "3"

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8082
  
  achatproject: 
   image: adamelamri/adamback:1.0.0
   container_name: achatproject
   restart: on-failure
   ports: 
    - 8089:8089
   depends_on:
    - mysqldb
    
  
      
