#docker-compose.yml
#version: "3"

services:
#  mysqldb:
#   image: mysql:8
#   container_name: mysqldb
#   restart: unless-stopped
#   environment:
#     MYSQL_ROOT_PASSWORD: root
#   volumes :
#     - /home/mysql/data:/var/lib/mysql
#
#  achatproject: 
#   image: adamelamri/adamback:1.0.0
#   container_name: achatproject
#   restart: on-failure
#   ports: 
#    - 8089:8089
#   depends_on:
#    - mysqldb
    
   angular-service: # The name of the service
      container_name: angularcontainer  
      #build: ./angulardockerproject # Location of our Dockerfile
      volumes: # Volume binding
        - './angulardockerproject:/usr/src/app' 
      ports: 
        - '4200:4200' # Port mapping
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200
