#docker-compose.yml
version: "3"

services:
  mysqldb:
   image: mysql:latest
   container_name: mysqldb
   restart: unless-stopped
   environment:
     MYSQL_ROOT_PASSWORD: root
   volumes :
     - /home/mysql/data:/var/lib/mysql
#     - ./dbdata:/var/lib/mysql

  achatproject: 
   image: ahmedtouil/achatback:1.0.0
   container_name: achatproject
   restart: on-failure
   ports: 
    - 8089:8089
   depends_on:
    - mysqldb
    
  # angular:
  #  image: ahmedtouil/achatfront:latest
  #  container_name: angularcontainer  
  #  ports: 
  #   - 4200:4200
  #  depends_on:
  #   - achatproject
      
