#docker-compose.yml
version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-containerFinal1:/var/lib/mysql:rw 

    
  achatproject: 
   image: adamelamri/adamback:1.0.0
   container_name: achatproject
   restart: on-failure
   ports: 
    - 8089:8089
   depends_on:
    - mysqldb
    
  
      
